In [1]:
# reading the CSV's and splitting into 70,30 - causal and non-causal
# combining train of causal& non-causal and test of causal& non-causal

import pandas as pd
from sklearn.model_selection import train_test_split

causal_df = pd.read_csv('causal_df.csv')
non_causal_df = pd.read_csv('non_causal_df.csv')

causal_train, causal_test = train_test_split(causal_df, test_size=0.3, random_state=42)
non_causal_train, non_causal_test = train_test_split(non_causal_df, test_size=0.3, random_state=42)

train_dataset = pd.concat([causal_train, non_causal_train], ignore_index=True)
test_dataset = pd.concat([causal_test, non_causal_test], ignore_index=True)

train_dataset = train_dataset.sample(frac=1).reset_index(drop=True)
test_dataset = test_dataset.sample(frac=1).reset_index(drop=True)

In [2]:
train_dataset

Unnamed: 0                                           sentence  causal
0            2549  the cause of death was asthma and old age whic...       1
1           24648  We report the case of a young HIV seropositive...       0
2           25116  Ocular examinations revealed intraocular press...       0
3           13818  It was concluded that ANCA is closely related ...       1
4           17761          ÊNot a Tesla or BMW, but it does the job.       0
...           ...                                                ...     ...
31659        8581         disinterred and reburied in israel in 1953       0
31660       27189  We observed an unexpectedly rapid rise in plat...       0
31661       25760  Laboratory studies yielded substantially incre...       0
31662       13898  ÊVolatility/PI Stock volatility is a percentag...       0
31663       13382                                      ÊPhillip Gast       0

[31664 rows x 3 columns]

In [3]:
# Drop the "Unnamed: 0" column from the train_dataset
train_dataset.drop("Unnamed: 0", axis=1, inplace=True)

In [4]:
train_dataset

sentence  causal
0      the cause of death was asthma and old age whic...       1
1      We report the case of a young HIV seropositive...       0
2      Ocular examinations revealed intraocular press...       0
3      It was concluded that ANCA is closely related ...       1
4              ÊNot a Tesla or BMW, but it does the job.       0
...                                                  ...     ...
31659         disinterred and reburied in israel in 1953       0
31660  We observed an unexpectedly rapid rise in plat...       0
31661  Laboratory studies yielded substantially incre...       0
31662  ÊVolatility/PI Stock volatility is a percentag...       0
31663                                      ÊPhillip Gast       0

[31664 rows x 2 columns]

In [5]:
train_dataset.shape

(31664, 2)

In [6]:
#train_dataset.to_csv("train_all_causal.csv")

In [7]:
test_dataset

Unnamed: 0                                           sentence  causal
0           26279  Ten of them were given the agent while the fem...       0
1           10427  ÊCRR members also collaborate with clinical co...       0
2           28739  A 10.5-year-old, castrated male shih tzu was p...       0
3           17477  ÊThe commercial drivers of insurance value and...       0
4            7859  zoft stress gum comes to the rescue with a com...       1
...           ...                                                ...     ...
13567       18726  ÊAlthough these things can happen along the wa...       0
13568       11958  ÊSuccess Rates Computed on a FY basis, success...       0
13569        5123  since 1958 it has held an annual lecture serie...       0
13570       18340  - - Gross Revenue - Price/Sales Ratio - Net In...       0
13571         563  chapter 2 examines civil liability for damage ...       1

[13572 rows x 3 columns]

In [8]:
test_dataset.drop("Unnamed: 0", axis=1, inplace=True)

In [9]:
test_dataset

sentence  causal
0      Ten of them were given the agent while the fem...       0
1      ÊCRR members also collaborate with clinical co...       0
2      A 10.5-year-old, castrated male shih tzu was p...       0
3      ÊThe commercial drivers of insurance value and...       0
4      zoft stress gum comes to the rescue with a com...       1
...                                                  ...     ...
13567  ÊAlthough these things can happen along the wa...       0
13568  ÊSuccess Rates Computed on a FY basis, success...       0
13569  since 1958 it has held an annual lecture serie...       0
13570  - - Gross Revenue - Price/Sales Ratio - Net In...       0
13571  chapter 2 examines civil liability for damage ...       1

[13572 rows x 2 columns]

In [10]:
test_dataset.shape

(13572, 2)

In [36]:
test_dataset.dropna(subset=['sentence'], inplace=True)

In [37]:
test_dataset

sentence  causal
0      Ten of them were given the agent while the fem...       0
1      ÊCRR members also collaborate with clinical co...       0
2      A 10.5-year-old, castrated male shih tzu was p...       0
3      ÊThe commercial drivers of insurance value and...       0
4      zoft stress gum comes to the rescue with a com...       1
...                                                  ...     ...
13567  ÊAlthough these things can happen along the wa...       0
13568  ÊSuccess Rates Computed on a FY basis, success...       0
13569  since 1958 it has held an annual lecture serie...       0
13570  - - Gross Revenue - Price/Sales Ratio - Net In...       0
13571  chapter 2 examines civil liability for damage ...       1

[13571 rows x 2 columns]

In [11]:
#test_dataset.to_csv("test_all_causal.csv")

In [12]:
test_dataset['sentence'].isnull().sum()

1

In [13]:
train_dataset['sentence'].isnull().sum()

2

In [14]:
null_mask = train_dataset['sentence'].isnull()

null_indices = train_dataset[null_mask].index

print(null_indices)

Index([1046, 17235], dtype='int64')


In [15]:
null_mask = test_dataset['sentence'].isnull()

null_indices = test_dataset[null_mask].index

print(null_indices)

Index([13162], dtype='int64')


In [16]:
#practice code

In [17]:
vocab = {'woodsmith',
 'each',
 'translit',
 'southwick',
 'circles',
 'dairy',
 'felbamate',
 'temples',
 'stripe',
 'east',
 'ffabdu'}

In [18]:
word2idx={'woodsmith': 0,
 'each': 1,
 'translit': 2,
 'southwick': 3,
 'circles': 4,
 'dairy': 5,
 'felbamate': 6,
 'temples': 7,
 'stripe': 8,
 'east': 9,
 'ffabdu': 10}

In [19]:
def prepare_sequence(seq, to_idx):  
    idxs = [to_idx[w] for w in seq]
    idxs = np.array(idxs)
    output_idxs = torch.from_numpy(idxs)
    output_idxs = output_idxs.type(torch.LongTensor).cuda()  
    return output_idxs

In [20]:
idxs = [word2idx[w] for w in vocab]

In [21]:
idxs

[6, 0, 1, 9, 3, 7, 8, 10, 5, 2, 4]

In [22]:
type(idxs)

list

In [23]:
for w in vocab:
    print(w)

felbamate
woodsmith
each
east
southwick
temples
stripe
ffabdu
dairy
translit
circles


In [24]:
word2idx['each']

1

In [25]:
import numpy as np
idxs = np.array(idxs) #converting  list into numpy

In [26]:
idxs

array([ 6,  0,  1,  9,  3,  7,  8, 10,  5,  2,  4])

In [27]:
type(idxs)

numpy.ndarray

In [28]:
import torch

In [29]:
output_idxs = torch.from_numpy(idxs)

In [30]:
output_idxs

tensor([ 6,  0,  1,  9,  3,  7,  8, 10,  5,  2,  4])

In [31]:
type(output_idxs)

torch.Tensor

In [32]:
output_idxs = output_idxs.type(torch.LongTensor).cuda()  

In [33]:
output_idxs

tensor([ 6,  0,  1,  9,  3,  7,  8, 10,  5,  2,  4], device='cuda:0')

In [34]:
type(output_idxs)

torch.Tensor